# This workflow handle pull requests
name: Receive pull_request
on: [pull_request_target]
jobs:
  approve: # to approve a workflow run(through github environment)
    name: Approve Job
    runs-on: ubuntu-latest
    steps:
      - name: Approve
        run: |
          echo For security reasons, all pull requests need to be approved first before running any automated CI.
          echo Thank you for your patience. 
  test:
    name: Test @ NodeJS - x86 - ubuntu-latest
    runs-on: ubuntu-latest
    needs: [approve]
    strategy:
      matrix:
        node-version: [14.x]
    environment:
      name: pr-reviews
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm prune
          npm i
      - name: Linting
        run: npm run lint
      - name: Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPO: ${{ secrets.GH_REPO }}
          WHMCSMP_LOGIN: ${{ secrets.WHMCSMP_LOGIN }}
          WHMCSMP_PASSWORD: ${{ secrets.WHMCSMP_PASSWORD }}
          WHMCSMP_PRODUCTID: ${{ secrets.WHMCSMP_PRODUCTID }}
          WHMCSMP_MINVERSION: ${{ secrets.WHMCSMP_MINVERSION }}
        run: npm run coverage

    
  
